Ttree:
  Flow:
    DevHelper:
      log:
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/PerformanceMetrics.log'
          createParentDirectories: TRUE
          severityThreshold: '%LOG_INFO%'
          maximumLogFileSize: 10485760
          logFilesToKeep: 5
          logMessageOrigin: FALSE
